/*
 * This file is generated by jOOQ.
 */
package com.springsecurityoauth2.model;


import com.springsecurityoauth2.model.tables.OauthAccessToken;
import com.springsecurityoauth2.model.tables.OauthApprovals;
import com.springsecurityoauth2.model.tables.OauthClientDetails;
import com.springsecurityoauth2.model.tables.OauthClientToken;
import com.springsecurityoauth2.model.tables.OauthCode;
import com.springsecurityoauth2.model.tables.OauthRefreshToken;
import com.springsecurityoauth2.model.tables.Permission;
import com.springsecurityoauth2.model.tables.Role;
import com.springsecurityoauth2.model.tables.RolePermission;
import com.springsecurityoauth2.model.tables.User;
import com.springsecurityoauth2.model.tables.UserRole;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.oauth_access_token</code>.
     */
    public static final OauthAccessToken OAUTH_ACCESS_TOKEN = OauthAccessToken.OAUTH_ACCESS_TOKEN;

    /**
     * The table <code>public.oauth_approvals</code>.
     */
    public static final OauthApprovals OAUTH_APPROVALS = OauthApprovals.OAUTH_APPROVALS;

    /**
     * The table <code>public.oauth_client_details</code>.
     */
    public static final OauthClientDetails OAUTH_CLIENT_DETAILS = OauthClientDetails.OAUTH_CLIENT_DETAILS;

    /**
     * The table <code>public.oauth_client_token</code>.
     */
    public static final OauthClientToken OAUTH_CLIENT_TOKEN = OauthClientToken.OAUTH_CLIENT_TOKEN;

    /**
     * The table <code>public.oauth_code</code>.
     */
    public static final OauthCode OAUTH_CODE = OauthCode.OAUTH_CODE;

    /**
     * The table <code>public.oauth_refresh_token</code>.
     */
    public static final OauthRefreshToken OAUTH_REFRESH_TOKEN = OauthRefreshToken.OAUTH_REFRESH_TOKEN;

    /**
     * The table <code>public.permission</code>.
     */
    public static final Permission PERMISSION = Permission.PERMISSION;

    /**
     * The table <code>public.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.role_permission</code>.
     */
    public static final RolePermission ROLE_PERMISSION = RolePermission.ROLE_PERMISSION;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>public.user_role</code>.
     */
    public static final UserRole USER_ROLE = UserRole.USER_ROLE;
}
