/*
 * This file is generated by jOOQ.
 */
package com.springsecurityoauth2.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolePermission implements Serializable {

    private static final long serialVersionUID = -165492622;

    private Integer roleId;
    private Integer permissionId;

    public RolePermission() {}

    public RolePermission(RolePermission value) {
        this.roleId = value.roleId;
        this.permissionId = value.permissionId;
    }

    public RolePermission(
        Integer roleId,
        Integer permissionId
    ) {
        this.roleId = roleId;
        this.permissionId = permissionId;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public Integer getPermissionId() {
        return this.permissionId;
    }

    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RolePermission (");

        sb.append(roleId);
        sb.append(", ").append(permissionId);

        sb.append(")");
        return sb.toString();
    }
}
