/*
 * This file is generated by jOOQ.
 */
package com.springsecurityoauth2.model.tables.daos;


import com.springsecurityoauth2.model.tables.OauthAccessToken;
import com.springsecurityoauth2.model.tables.records.OauthAccessTokenRecord;

import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OauthAccessTokenDao extends DAOImpl<OauthAccessTokenRecord, com.springsecurityoauth2.model.tables.pojos.OauthAccessToken, String> {

    /**
     * Create a new OauthAccessTokenDao without any configuration
     */
    public OauthAccessTokenDao() {
        super(OauthAccessToken.OAUTH_ACCESS_TOKEN, com.springsecurityoauth2.model.tables.pojos.OauthAccessToken.class);
    }

    /**
     * Create a new OauthAccessTokenDao with an attached configuration
     */
    public OauthAccessTokenDao(Configuration configuration) {
        super(OauthAccessToken.OAUTH_ACCESS_TOKEN, com.springsecurityoauth2.model.tables.pojos.OauthAccessToken.class, configuration);
    }

    @Override
    public String getId(com.springsecurityoauth2.model.tables.pojos.OauthAccessToken object) {
        return object.getAuthenticationId();
    }

    /**
     * Fetch records that have <code>token_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.springsecurityoauth2.model.tables.pojos.OauthAccessToken> fetchRangeOfTokenId(String lowerInclusive, String upperInclusive) {
        return fetchRange(OauthAccessToken.OAUTH_ACCESS_TOKEN.TOKEN_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>token_id IN (values)</code>
     */
    public List<com.springsecurityoauth2.model.tables.pojos.OauthAccessToken> fetchByTokenId(String... values) {
        return fetch(OauthAccessToken.OAUTH_ACCESS_TOKEN.TOKEN_ID, values);
    }

    /**
     * Fetch records that have <code>token BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.springsecurityoauth2.model.tables.pojos.OauthAccessToken> fetchRangeOfToken(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(OauthAccessToken.OAUTH_ACCESS_TOKEN.TOKEN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>token IN (values)</code>
     */
    public List<com.springsecurityoauth2.model.tables.pojos.OauthAccessToken> fetchByToken(byte[]... values) {
        return fetch(OauthAccessToken.OAUTH_ACCESS_TOKEN.TOKEN, values);
    }

    /**
     * Fetch records that have <code>authentication_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.springsecurityoauth2.model.tables.pojos.OauthAccessToken> fetchRangeOfAuthenticationId(String lowerInclusive, String upperInclusive) {
        return fetchRange(OauthAccessToken.OAUTH_ACCESS_TOKEN.AUTHENTICATION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>authentication_id IN (values)</code>
     */
    public List<com.springsecurityoauth2.model.tables.pojos.OauthAccessToken> fetchByAuthenticationId(String... values) {
        return fetch(OauthAccessToken.OAUTH_ACCESS_TOKEN.AUTHENTICATION_ID, values);
    }

    /**
     * Fetch a unique record that has <code>authentication_id = value</code>
     */
    public com.springsecurityoauth2.model.tables.pojos.OauthAccessToken fetchOneByAuthenticationId(String value) {
        return fetchOne(OauthAccessToken.OAUTH_ACCESS_TOKEN.AUTHENTICATION_ID, value);
    }

    /**
     * Fetch records that have <code>user_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.springsecurityoauth2.model.tables.pojos.OauthAccessToken> fetchRangeOfUserName(String lowerInclusive, String upperInclusive) {
        return fetchRange(OauthAccessToken.OAUTH_ACCESS_TOKEN.USER_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_name IN (values)</code>
     */
    public List<com.springsecurityoauth2.model.tables.pojos.OauthAccessToken> fetchByUserName(String... values) {
        return fetch(OauthAccessToken.OAUTH_ACCESS_TOKEN.USER_NAME, values);
    }

    /**
     * Fetch records that have <code>client_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.springsecurityoauth2.model.tables.pojos.OauthAccessToken> fetchRangeOfClientId(String lowerInclusive, String upperInclusive) {
        return fetchRange(OauthAccessToken.OAUTH_ACCESS_TOKEN.CLIENT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>client_id IN (values)</code>
     */
    public List<com.springsecurityoauth2.model.tables.pojos.OauthAccessToken> fetchByClientId(String... values) {
        return fetch(OauthAccessToken.OAUTH_ACCESS_TOKEN.CLIENT_ID, values);
    }

    /**
     * Fetch records that have <code>authentication BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.springsecurityoauth2.model.tables.pojos.OauthAccessToken> fetchRangeOfAuthentication(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(OauthAccessToken.OAUTH_ACCESS_TOKEN.AUTHENTICATION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>authentication IN (values)</code>
     */
    public List<com.springsecurityoauth2.model.tables.pojos.OauthAccessToken> fetchByAuthentication(byte[]... values) {
        return fetch(OauthAccessToken.OAUTH_ACCESS_TOKEN.AUTHENTICATION, values);
    }

    /**
     * Fetch records that have <code>refresh_token BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.springsecurityoauth2.model.tables.pojos.OauthAccessToken> fetchRangeOfRefreshToken(String lowerInclusive, String upperInclusive) {
        return fetchRange(OauthAccessToken.OAUTH_ACCESS_TOKEN.REFRESH_TOKEN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>refresh_token IN (values)</code>
     */
    public List<com.springsecurityoauth2.model.tables.pojos.OauthAccessToken> fetchByRefreshToken(String... values) {
        return fetch(OauthAccessToken.OAUTH_ACCESS_TOKEN.REFRESH_TOKEN, values);
    }
}
